### ISSUE TITLE
Sends Alt instead Space on Debian/GNOME

### ISSUE THREAD

**Issue by To1ne** [keyboardio/Kaleidoscope-SpaceCadet#12]
My SpaceCadet plugin was working perfectly on macOS. But now I have my M01 connected to Debian with GNOME. I have configured right Alt to be Space, when tapped briefly.

But when tapped briefly I'm getting Alt. And when tapped briefly twice, it sends a Space.

I would love to help fix this, but I'm not sure how to investigate. So let me know if there is anything I can do to help?

**Comment by To1ne** [comment]
Should have looked in the issues first. Might be a duplicate of #9.

Let me ensure I have the latest version and try again.

**Comment by advisoray** [comment]
The version that ships in the Arduino plugins is old and likely has this issue. Let me know if this isn't resolved with the newest version and I'll take a look.

What was happening was we were always sending the original keypresses in addition to the injected key. On Mac this was fine, but on Windows this captured the toolbar when Alt was sent, and this captured the toolbar and ignored the injected button. I suspect similar behavior is happening in Gnome.

The fixed code keeps track of the original keypress but suppresses it until the release happens (sending the alternative key), the timeout happens (where it will send the original key), or another key is pressed (sending the default key). This makes it more important to set your timeouts low enough that you can still tap to get the alternative keys, but not so high that you block any actions you might take (ctrl+click or alt+click or shift+click may be blocked).

The new code also allows setting a key to enable or disable SpaceCadet. I am thinking of making one final change to allow optional momentary killing of the functionality if Fn is held down, but we will see.

**Comment by To1ne** [comment]
@advisoray Thanks for the detailed explanation.

I'm happy to report that with the latest version everything is working fine!

Many thanks!
