### ISSUE TITLE
Default configuration doesn't work

### ISSUE THREAD

**Issue by jamesnvc** [keyboardio/Kaleidoscope-SpaceCadet#5]
In the readme, it states that one should be able to just use the plugin and get the default behaviour of shifts-as-spaces.  However, doing so seems to result in an error when the keyboard boots.
I see that the code creates a default constructor for the SpaceCadet object, so I'm not sure if this is an inaccuracy in the documentation or an error in the code.

**Comment by advisoray** [comment]
The documentation should be right. I will take a look tonight and see if I
can reproduce, and if I can reproduce I will fix it.

**Comment by adkron** [comment]
workaround: Us an explicit configuration until this is fixed.

**Comment by advisoray** [comment]
I was able to reproduce.  Additionally, I was able to fix it.  Creating a pull request to solve the issue.

**Comment by algernon** [comment]
This has been fixed by #6 for a while, closing as such.
