### ISSUE TITLE
Modifier flags are cleared a little enthusiastically

### ISSUE THREAD

**Issue by pdcawley** [keyboardio/Kaleidoscope-SpaceCadet#7]
Consider the following setup (yes, it's weird, but I've been a maltron user for years and those beasts a _much_ larger thumb cluster than the Model 01). 

```
  static kaleidoscope::SpaceCadet::KeyBinding spacecadetmap[] = {
    {Key_LeftShift, Key_E, 200}
    , {Key_RightShift, Key_Spacebar, 200}
    , {Key_RightGui, Key_Enter, 200}
    , SPACECADET_MAP_END
  };

```

When I try to type a capital E, the log in my Karabiner-EventViewer looks like this:

eventType | code | name | flags
----------|------|------|------
FlagsChanged | 0x3c | right_shift | Shift
FlagsChanged | 0x38 | left_shift | Shift
FlagsChanged | 0x38 | left_shift | Shift
KeyDown | 0xe | e | 
FlagsChanged | 0x3c | right_shift | Shift
KeyUp | 0xe | e | Shift
FlagsChanged | 0x3c | right_shift |

What I'd _like_ it to look like is this.

eventType | code | name | flags
----------|------|------|------
FlagsChanged | 0x3c | right_shift | Shift
FlagsChanged | 0x38 | left_shift | Shift
FlagsChanged | 0x38 | left_shift | Shift
KeyDown | 0xe | e | Shift
KeyUp | 0xe | e | Shift
FlagsChanged | 0x3c | right_shift |

I think the problem might be that we need to keep a count of the number of held down keys currently contributing to a given modifier flag, but I need to dig a bit deeper into that before I'm prepared to swear to it. I've posted the issue on the off chance that someone will beat me to the fix.

**Comment by algernon** [comment]
This is a known issue of scan order and some plugins, a bit more details can be read [on the forums](https://community.keyboard.io/t/at-what-points-can-plugins-act/652/3?u=algernon).

The short version is that we clear the report each cycle, to avoid having to do manual counting. This has the side effect that if plugins, macros or whatever wants to look at the current report to see if any modifiers are active, they'll only see keys processed before them. Similarly, plugins that send a report early, send partial reports. This is what happens in this case too.

It isn't trivial to fix...

I'll try to dump by brain about the possibilities I see, as soon as I have a little time.

**Comment by pdcawley** [comment]
Does this mean that it might be possible to have a simple layout with no fancy key effects that, by virtue of the keyscan order sends unmodified events? That seems… less than optimal.

**Comment by algernon** [comment]
No, no need to worry about that. This problem only affects things that either send an out-of-band report, before the whole keymap has been processed, or those that want to base their action on the current state of the keyboard.

This issue does *not* affect the basic functionality of the keyboard.

**Comment by pdcawley** [comment]
It seemed unlikely.

**Comment by pdcawley** [comment]
If `eventHandlerHook` has the option to return a list of Keys rather than just a Key, I think SpaceCadet functionality can be made to work without needing to touch anything but its own state. It certainly shouldn't need to mess with the modifier state, I don't think.

Am I missing anything with this pseudocode:

```
if (!(key.wasToggledOn || key.wasToggledOff)) {
  return key;
}
else if (key.wasToggledOn) {
  thisEntry = SpaceCaded.keyMap[key];
  foreach entry in SpaceCadet.keyMap {
  if (entry != thisEntry) {
    entry.wasChorded = TRUE;
  }
  else {
    entry.wasChorded = FALSE;
    entry.tapExpiresAt = now() + entry.tapTimeout;   
  }
  SpaceCadet.keyMap[key].wasChorded = FALSE;
}
else if (key.wasToggledOff) {
    entry = SpaceCadet.keyMap[key]
  
  if (entry.wasChorded || (now() > entry.tapExpiresAt)) {
    return key;
  }
  else {
    return KeySequence(key, Key(DOWN, entry.tappedKey), Key(UP, entry.tappedKey));
  }
}
```

This should be robust in the face of everything but two SpaceCadet keys being hit in the same cycle and released together.
