### ISSUE TITLE
Placing { on Key_LeftAlt still sends alt key event

### ISSUE THREAD

**Issue by pian0** [keyboardio/Kaleidoscope-SpaceCadet#9]
I turned on the extra replacements for the other thumb buttons and everything works great in OS X, but on Windows the Alt key is causing me trouble. Here's the behavior I have observed:

- Tap Key_LeftAlt: nothing, if the application has a menu bar (expected: type `{` character)
- Hold and release Key_LeftAlt longer than timeout value: only `alt` is sent, highlighting the menu bar (expected behavior)
- Hold and release, then tap while menu is highlighted: unselect menu and type `{` (expected: unselect menu)

It seems like SpaceCadet doesn't swallow the Alt event and Windows interprets both `alt` and `{` being sent, maybe in that order or at the same time? Is there some change I can make to my layout so that the modifier is not sent when the alternate key is triggered?

**Comment by advisoray** [comment]
It wasn't doing this behavior in a previous releas, if I recall correctly. I am on vacation right now and don't have access to the board to test on, but I should be able to take a look at this and fix it later this week, if @algernon doesn't get to it first.

**Comment by advisoray** [comment]
Fix completed and PR created: https://github.com/keyboardio/Kaleidoscope-SpaceCadet/pull/10

**Comment by advisoray** [comment]
The fix for this was merged in a while ago, so this can be closed.

**Comment by pian0** [comment]
This appears to be fixed with the latest code. I’ve noticed some strange behavior that’s not quite right but I haven’t had a chance to write it up. I’ll open a new issue when I do so.
